CREATE TABLE user(
    idx INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userid VARCHAR(10) NOT NULL
);

INSERT INTO USER(USERID) VALUES('test1');
INSERT INTO USER(USERID) VALUES('test2');
INSERT INTO USER(USERID) VALUES('test3');